name: cii
description: "CII - Snagging Application"
publish_to: 'none'
version: 1.0.10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  json_annotation: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  yaml: ^3.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+4
  path_provider: ^2.1.0
  path: ^1.8.3
  image_painter: ^0.7.1
  pdf: ^3.11.3
  share_plus: ^12.0.0
  fl_chart: ^0.66.2
  pie_chart: ^5.4.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  open_file: ^3.3.2
  image: ^4.1.3
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  csv: ^6.0.0
  package_info_plus: ^9.0.0
  workmanager: ^0.9.0
  url_launcher: ^6.2.1
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/splash/SplashScreen.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Roboto-Light.ttf
          weight: 300
  assets:
    - lib/assets/icons/png/project_icon.png
    - lib/assets/icons/png/snag_icon.png
    - lib/assets/icons/png/details_icon.png
    - lib/assets/icons/png/priority_low_icon.png
    - lib/assets/icons/png/priority_medium_icon.png
    - lib/assets/icons/png/priority_high_icon.png
    - lib/assets/icons/png/priority_low_icon_16.png
    - lib/assets/icons/png/priority_high_icon_16.png
    - lib/assets/icons/png/image_upload.png
    - lib/assets/icons/png/assignee_unassigned.png
    - lib/assets/icons/png/assignee_assigned.png
    - lib/assets/splash/SplashScreen.png

    - lib/assets/logo/CII_logo.png

    # Terms and Conditions
    - lib/assets/text/terms_conditions.txt
